/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package turf.booking.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunny
 */
public class AllTurfDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form AllTurfDetails
     */
    public AllTurfDetails() {
        initComponents();
     try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databseurl = "jdbc:mysql://localhost/turf";
            //String insertQuery = "insert into user_details values('"+i+"','"+firstname+"','"+lastname+"','"+username+"','"+password+"','"+email+"','"+no+"')";
            
            Connection con = DriverManager.getConnection(databseurl,"root","");
            //PreparedStatment ps = new PreparedStatement();
            Statement st = con.createStatement();
            
             String selectQuery = "select * from turf_details";// where username='"+user+"' and password='"+password+"'";
            //System.out.println(selectQuery);
            
            ResultSet rs = st.executeQuery(selectQuery);
            ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            
            DefaultTableModel dtm =(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            
            Vector v = new Vector();
            
            int i;
            while(rs.next())
            {
                
                
                for(i=0;i<=n;i++)
                {
                    v.add(rs.getString("id"));
                    v.add(rs.getString("turf_name"));
                    v.add(rs.getString("turf_location"));
                    v.add(rs.getString("turf_date"));
                    v.add(rs.getString("turf_time"));
                    v.add(rs.getString("turf_price"));
                }   
                
                dtm.addRow(v);           
            }
            
        
    }
        catch(Exception e)
        {
        
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("All Turf Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sr.No", "Turf Name", "Turf Location", "Date", "Time", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
